Repository wisemen-digital/flutter-playbook, pull requests merged in 2025-04, with the labels that each got.

#4 Add documentation for repositories and managers
  .vitepress/config.ts
  package-lock.json
  package.json
  src/architecture.md
  src/architecture/managers.md
  src/architecture/repository.md
Labels: 📃 S PR, ✨ feature

#3 Added publish action
  .github/workflows/publish-docs.yml
Labels: 📃 XS PR

#5 Added theme and feature
  .vitepress/config.ts
  pnpm-lock.yaml
  src/architecture/feature.md
  src/architecture/theming.md
  src/public/architecture.png
Labels: 📃 XL PR, ✨ feature

#8 Changed image path for ci
  src/architecture/layers.md
Labels: 📃 XS PR

#9 Fixed dead links
  src/architecture.md
  src/architecture/managers.md
  src/architecture/theming.md
Labels: 📃 XS PR
